# Data Exploration 03

You're working on an exhibit for a local museum called "The Titanic Disaster". They've asked you to analyze the passenger manifests and see if you can find any interesting information for the exhibit.

The museum curator is particularly interested in why some people might have been more likely to survive than others.

## Part 1: Import Polars and load the data

Remember to import Pandas the conventional way. If you've forgotten how, you may want to review [Data Exploration 01](https://byui-cse.github.io/cse450-course/module-01/exploration-01.html).

The dataset for this exploration is stored at the following url:

[https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv](https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv)

There are lots of ways to load data into your workspace. The easiest way in this case is to [ask Polars to do it for you](https://docs.pola.rs/user-guide/getting-started/#reading-writing).

### Initial Data Analysis
Once you've loaded the data, it's a good idea to poke around a little bit to find out what you're dealing with.

Some questions you might ask include:

* What does the data look like?
* What kind of data is in each column?
* Do any of the columns have missing values?

In [1]:
# Part 1: Enter your code below to import Pandas according to the
# conventional method. Then load the dataset into a Pandas dataframe.
import polars as pl
titanic = pl.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/titanic.csv')

# Write any code needed to explore the data by seeing what the first few
# rows look like. Then display a technical summary of the data to determine
# the data types of each column, and which columns have missing data.
titanic.head()

shape: (5, 12)
┌─────────────┬──────────┬────────┬───────────────────┬───┬───────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Ticket    ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---       ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ str      ┆ i64    ┆ str               ┆   ┆ str       ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪═══════════╪═════════╪═══════╪══════════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ A/5 21171 ┆ 7.25    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Harris            ┆   ┆           ┆         ┆       ┆          │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ PC 17599  ┆ 71.2833 ┆ C85   ┆ C        │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆           ┆         ┆       ┆          │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ STON/O2.  ┆ 7.925   ┆ null  ┆ S        │
│             ┆          ┆        ┆ Laina             ┆   ┆ 3101282   ┆         ┆       ┆          │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ 113803    ┆ 53.1    ┆ C123  ┆ S        │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆           ┆         ┆       ┆          │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr.        ┆ … ┆ 373450    ┆ 8.05    ┆ null  ┆ S        │
│             ┆          ┆        ┆ William Henry     ┆   ┆           ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴───────────────────┴───┴───────────┴─────────┴───────┴──────────┘

In [2]:
display(titanic.schema)
display(titanic.shape)
display(titanic.null_count())

Schema([('PassengerId', Int64),
        ('Survived', String),
        ('Pclass', Int64),
        ('Name', String),
        ('Sex', String),
        ('Age', Float64),
        ('SibSp', Int64),
        ('Parch', Int64),
        ('Ticket', String),
        ('Fare', Float64),
        ('Cabin', String),
        ('Embarked', String)])

(891, 12)

shape: (1, 12)
┌─────────────┬──────────┬────────┬──────┬───┬────────┬──────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name ┆ … ┆ Ticket ┆ Fare ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---  ┆   ┆ ---    ┆ ---  ┆ ---   ┆ ---      │
│ u32         ┆ u32      ┆ u32    ┆ u32  ┆   ┆ u32    ┆ u32  ┆ u32   ┆ u32      │
╞═════════════╪══════════╪════════╪══════╪═══╪════════╪══════╪═══════╪══════════╡
│ 0           ┆ 0        ┆ 0      ┆ 0    ┆ … ┆ 0      ┆ 0    ┆ 687   ┆ 2        │
└─────────────┴──────────┴────────┴──────┴───┴────────┴──────┴───────┴──────────┘

## Part 2: Initial Exploration

Using your visualization library of choice, let's first look at some features in isolation. Generate visualizations showing:

- A comparison of the total number of passengers who survived compared to those that died.
- A comparison of the total number of males compared to females
- A histogram showing the distribution of sibling/spouse counts
- A histogram showing the distribution of parent/child counts

In [3]:
# Add the lets-plot library
%pip install lets-plot
from lets_plot import *
LetsPlot.setup_html()

Collecting lets-plot
  Downloading lets_plot-4.9.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (12 kB)
Collecting pypng (from lets-plot)
  Downloading pypng-0.20220715.0-py3-none-any.whl.metadata (13 kB)
Collecting palettable (from lets-plot)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from lets-plot) (11.3.0)
Downloading lets_plot-4.9.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (7.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 61.5 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 24.4 MB/s eta 0:00:00
Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 3.9 MB/s eta 0:00:00
Installing collected packages: pypng, palettable, lets-plot
Successfully installed lets-plot-4.9.0 palettable-3.3.3 pypng-0.20220715.0

In [5]:
# Part 2: # Write the code needed to generate the visualizations specified.

# A comparison of the total number of passengers who survived compared to those that died.

(
    ggplot(data=titanic, mapping=aes(x='Survived', fill='Survived'))
    + geom_bar()
    + labs(
        title='Titanic Survival Statistics',
        x='Survived',
        y='Number of Passengers'
    )
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
)

In [6]:
# A comparison of the total number of males compared to females

(
    ggplot(data=titanic.with_columns(pl.col('Sex').str.to_titlecase()), mapping=aes(x='Sex', fill='Sex'))
    + geom_bar()
    + labs(
        title='Titanic Gender Statistics',
        x='Sex',
        y='Number of Passengers'
    )
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
)

In [7]:
# A histogram showing the distribution of sibling/spouse counts

(
    ggplot(data=titanic, mapping=aes(x='SibSp'))
    + geom_histogram()
    + scale_x_discrete(limits=list(range(0,9)))
    + labs(
        title='Sibling & Spouse Count Distribution',
        x='Siblings and Spouses',
        y='Number of Passengers'
    )
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
)

In [8]:
# A histogram showing the distribution of parent/child counts
(
    ggplot(data=titanic, mapping=aes(x='Parch'))
    + geom_histogram()
    + scale_x_discrete(limits=list(range(0,7)))
    + labs(
        title='Parent & Child Count Distribution',
        x='Parents and Children',
        y='Number of Passengers'
    )
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
)

## Part 3: Pairwise Comparisons
Use your visualization library of choice to look at how the survival distribution varied across different groups.

- Choose some features that you think might have had some influence over the likelihood of a titanic passenger surviving.

- For each of those features, generate a chart for each feature showing the survival distributions when taking that feature into account

In [9]:
# Write the code to explore how different features affect the survival distribution
# Gender seems to make a big difference. Could Jack have fit on that door?
(
    ggplot(data=titanic.with_columns(pl.col('Sex').str.to_titlecase()), mapping=aes(x='Survived', fill='Survived'))
    + geom_bar()
    + labs(
        title='How Did Passenger Gender Affect Survival',
        x='Survived',
        y='Total Survivors'
    )
    + facet_grid(x='Sex')
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
)

In [10]:
# The better class ticket you had, the more likely you were to survive.

# Let's look at survivors by ticket class
(
    ggplot(data=titanic.with_columns(Ticket = "Class " + pl.col('Pclass').cast(pl.String)), mapping=aes(x='Survived', fill='Survived'))
    + geom_bar()
    + labs(
        title='Survival Rates by Ticket Class',
        x='Survived',
        y='Number of Passengers'
    )
    + facet_grid(x='Ticket')
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
)

## Part 4: Feature Engineering

The museum curator wonders if the passenger's rank and title might have anything to do with whether or not they survived. Since this information is embedded in their name, we'll use "feature engineering" to create two new columns:

- Title: The passenger's title
- Rank: A boolean (true/false) indicating if a passenger was someone of rank.

For the first new column, you'll need to find a way to [extract the title portion of their name](https://pandas.pydata.org/docs/getting_started/intro_tutorials/10_text_data.html). Be sure to clean up any whitespace or extra punctuation.

For the second new column, you'll need to first look at a summary of your list of titles and decide what exactly constitutes a title of rank. Will you include military and eccelsiastical titles? Once you've made your decision, create the second column.

You may want to review prior Data Explorations for tips on creating new columns and checking for lists of values.

In [11]:
# Enter the code needed to create the two new columns

# Names seems to be in this format:
#   Braund, Mr. Owen Harris
#   <Last Name>, Title. <Given Names>

# Let's break down this code:
# "Title =" assigns whatever follows this expression as the value of the column named Title
# .str.extract(...) - Uses the string extract function to extract using a regular expression
# Regular Expression: ', (.+?)\\.'
#    ", "    start with a comma then a space
#    ( ... ) parenthesis to extract the part that matches in the middle
#    ".+?"   the . matches any character, the + says one or more, and the ? means
#            take as few as possible
#    "\\."   means an actual period - the first \ excapes the second \ so that the
#            python string only treats it as a single \, and because the . follows
#            the \ you get \. which says an actual period rather than any character
# the 1 means the 1st group of parenthesis is extracted as the Title
titanic = titanic.with_columns(Title = pl.col('Name').str.extract(', (.+?)\\.', 1))
titanic.head()

shape: (5, 13)
┌─────────────┬──────────┬────────┬────────────────────┬───┬─────────┬───────┬──────────┬───────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name               ┆ … ┆ Fare    ┆ Cabin ┆ Embarked ┆ Title │
│ ---         ┆ ---      ┆ ---    ┆ ---                ┆   ┆ ---     ┆ ---   ┆ ---      ┆ ---   │
│ i64         ┆ str      ┆ i64    ┆ str                ┆   ┆ f64     ┆ str   ┆ str      ┆ str   │
╞═════════════╪══════════╪════════╪════════════════════╪═══╪═════════╪═══════╪══════════╪═══════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr. Owen   ┆ … ┆ 7.25    ┆ null  ┆ S        ┆ Mr    │
│             ┆          ┆        ┆ Harris             ┆   ┆         ┆       ┆          ┆       │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs. John ┆ … ┆ 71.2833 ┆ C85   ┆ C        ┆ Mrs   │
│             ┆          ┆        ┆ Bradley (Fl…       ┆   ┆         ┆       ┆          ┆       │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen, Miss.   ┆ … ┆ 7.925   ┆ null  ┆ S        ┆ Miss  │
│             ┆          ┆        ┆ Laina              ┆   ┆         ┆       ┆          ┆       │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle, Mrs.     ┆ … ┆ 53.1    ┆ C123  ┆ S        ┆ Mrs   │
│             ┆          ┆        ┆ Jacques Heath (…   ┆   ┆         ┆       ┆          ┆       │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr. William ┆ … ┆ 8.05    ┆ null  ┆ S        ┆ Mr    │
│             ┆          ┆        ┆ Henry              ┆   ┆         ┆       ┆          ┆       │
└─────────────┴──────────┴────────┴────────────────────┴───┴─────────┴───────┴──────────┴───────┘

In [12]:
# Now see what values we have (add the config so that you can see all the rows):
with pl.Config(tbl_rows=20):
    display(titanic.group_by(pl.col('Title')).len())

shape: (17, 2)
┌──────────────┬─────┐
│ Title        ┆ len │
│ ---          ┆ --- │
│ str          ┆ u32 │
╞══════════════╪═════╡
│ Mr           ┆ 517 │
│ Sir          ┆ 1   │
│ Miss         ┆ 182 │
│ Dr           ┆ 7   │
│ Ms           ┆ 1   │
│ Rev          ┆ 6   │
│ Don          ┆ 1   │
│ Mlle         ┆ 2   │
│ Master       ┆ 40  │
│ the Countess ┆ 1   │
│ Jonkheer     ┆ 1   │
│ Col          ┆ 2   │
│ Mrs          ┆ 125 │
│ Mme          ┆ 1   │
│ Major        ┆ 2   │
│ Lady         ┆ 1   │
│ Capt         ┆ 1   │
└──────────────┴─────┘

In [13]:
# Some things I think qualify as titles of rank:
titanic = titanic.with_columns(pl.col('Title').is_in(['Dr', 'Rev', 'Major', 'Col', 'Capt', 'Lady', 'Sir', 'Don', 'the Countess', 'Jonkheer']).alias('Rank'))
titanic.head()

shape: (5, 14)
┌─────────────┬──────────┬────────┬─────────────────────────┬───┬───────┬──────────┬───────┬───────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name                    ┆ … ┆ Cabin ┆ Embarked ┆ Title ┆ Rank  │
│ ---         ┆ ---      ┆ ---    ┆ ---                     ┆   ┆ ---   ┆ ---      ┆ ---   ┆ ---   │
│ i64         ┆ str      ┆ i64    ┆ str                     ┆   ┆ str   ┆ str      ┆ str   ┆ bool  │
╞═════════════╪══════════╪════════╪═════════════════════════╪═══╪═══════╪══════════╪═══════╪═══════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr. Owen Harris ┆ … ┆ null  ┆ S        ┆ Mr    ┆ false │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs. John      ┆ … ┆ C85   ┆ C        ┆ Mrs   ┆ false │
│             ┆          ┆        ┆ Bradley (Fl…            ┆   ┆       ┆          ┆       ┆       │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen, Miss. Laina  ┆ … ┆ null  ┆ S        ┆ Miss  ┆ false │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle, Mrs. Jacques  ┆ … ┆ C123  ┆ S        ┆ Mrs   ┆ false │
│             ┆          ┆        ┆ Heath (…                ┆   ┆       ┆          ┆       ┆       │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr. William      ┆ … ┆ null  ┆ S        ┆ Mr    ┆ false │
│             ┆          ┆        ┆ Henry                   ┆   ┆       ┆          ┆       ┆       │
└─────────────┴──────────┴────────┴─────────────────────────┴───┴───────┴──────────┴───────┴───────┘

### Revisit Visualizations
Now that you have the new columns in place. Revisit the pairwise comparison plots to see if the new columns reveal any interesting relationships. Don't forget to check with and without different `column` variations.

In [14]:
# Enter the code needed to recheck the pairwise comparison. Try different variations of the column channel.

# Let's look at survivors by title using a % of total chart for this
(
    ggplot(data=titanic, mapping=aes(x='Survived', fill='Survived'))
    + geom_bar()
    + labs(
        title='Survival Rates by Title',
        x='Survived',
        y='Number of Passengers'
    )
    + facet_grid(x='Title')
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
    + ggsize(1000,300)
)

In [15]:
# Rank titles only
(
    ggplot(data=titanic.filter(pl.col('Rank') == True), mapping=aes(x='Survived', fill='Survived'))
    + geom_bar()
    + labs(
        title='Survival Rates by Title',
        x='Survived',
        y='Number of Passengers'
    )
    + facet_grid(x='Title')
    + theme(
        plot_title=element_text(size=14, face='bold', hjust=0.5),
        axis_title=element_text(size=12, face='bold'),
        legend_position='none'
    )
    + ggsize(1000,300)
)

## Part 5: Encoding

The museum has partnered with a data science group to build some interactive predicitive models using the titanic passenger data.

Many machine learning algorithms require categorical features to be **encoded** as numbers.

There are two approaches to this, label encoding (sometimes called factorization), and "one-hot" encoding.

### Label Encoding

Label encoding creates numeric labels for each categorical value. For example, imagine we have a feature in the data called `Pet` with these values for the first five rows: `['Dog', 'Cat', 'Dog', 'Dog', 'Bird']`.

We could create a new feature called `Pet_Encoded` where those values are represented as: `[0, 1, 0, 0, 2]`. Where `0 = Dog, 1 = Cat, and 2 = Bird`.

We first use `.cast(pl.Categorical)` to turn it into a categorical variable and then use [`.to_physical()`](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.to_physical.html) to convert it to the enumerated value

    myData = myData.with_columns(pl.col('Pet').cast(pl.Categorical).to_physical().alias('Pet_Encoded'))

In our machine learning algorithm could use the new `Pet_Encoded` feature in place of the `Pet` feature.

In [16]:
# Create a new column in the dataset called "Sex_Encoded" containing the
# label encoded values of the "Sex" column
titanic = titanic.with_columns(pl.col('Sex').cast(pl.Categorical).to_physical().alias('Sex_Encoded'))
titanic.head()

shape: (5, 15)
┌─────────────┬──────────┬────────┬───────────────────┬───┬──────────┬───────┬───────┬─────────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name              ┆ … ┆ Embarked ┆ Title ┆ Rank  ┆ Sex_Encoded │
│ ---         ┆ ---      ┆ ---    ┆ ---               ┆   ┆ ---      ┆ ---   ┆ ---   ┆ ---         │
│ i64         ┆ str      ┆ i64    ┆ str               ┆   ┆ str      ┆ str   ┆ bool  ┆ u32         │
╞═════════════╪══════════╪════════╪═══════════════════╪═══╪══════════╪═══════╪═══════╪═════════════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr. Owen  ┆ … ┆ S        ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ Harris            ┆   ┆          ┆       ┆       ┆             │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs.     ┆ … ┆ C        ┆ Mrs   ┆ false ┆ 1           │
│             ┆          ┆        ┆ John Bradley (Fl… ┆   ┆          ┆       ┆       ┆             │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen, Miss.  ┆ … ┆ S        ┆ Miss  ┆ false ┆ 1           │
│             ┆          ┆        ┆ Laina             ┆   ┆          ┆       ┆       ┆             │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle, Mrs.    ┆ … ┆ S        ┆ Mrs   ┆ false ┆ 1           │
│             ┆          ┆        ┆ Jacques Heath (…  ┆   ┆          ┆       ┆       ┆             │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr.        ┆ … ┆ S        ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ William Henry     ┆   ┆          ┆       ┆       ┆             │
└─────────────┴──────────┴────────┴───────────────────┴───┴──────────┴───────┴───────┴─────────────┘

### One-Hot Encoding

One problem with label encoding is that it can make a categorical variable appear as if it contains a quantitative relationship between its values.

In the example above, is Bird twice as important as Cat? Some algorithms might interpret those values that way.

One-Hot encoding avoids this problem by creating a new feature for each category. The value of the new feature is either `0` (is not this value) or `1` (is this value).

In pandas, we can use the [to_dummies()](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.to_dummies.html#) method to deal with this problem:

    myEncodedData = myData.to_dummies(columns=['Pet'])

In the case of our `Pet` example, the new features created by `get_dummies()` would be:

| Pet_is_Dog | Pet_is_Cat | Pet_is_Bird |
|:----------:|:----------:|:-----------:|
|      1     |      0     |      0      |
|      0     |      1     |      0      |
|      1     |      0     |      0      |
|      1     |      0     |      0      |
|      0     |      0     |      1      |

Notice that for our data, if `Pet_is_Bird` = 0 and `Pet_is_Cat` = 0, we know that the pet has to be a dog. So the `Pet_is_Dog` column contains redundant information. When this happens, we say that our data contains a _multicollinearity_ problem.

To avoid this, we can tell `to_dummies()` that we want to get rid of one of the columns using the `drop_first` parameter:

    myEncodedData = myData.to_dummies(columns=['Pet'], drop_first=True)

The main disadvantage to One-Hot encoding is that if the feature you're encoding has a lot of different values, it can result in a lot of extra features. This can sometimes lead to poor performance with some types of algorithms.

In [17]:
# Use the polars to_dummies() method to one-hot encode the Embarked column.

titanicEncoded = titanic.to_dummies(columns=['Embarked'], drop_first=True)
titanicEncoded.head()

shape: (5, 17)
┌─────────────┬──────────┬────────┬───────────────┬───┬──────────────┬───────┬───────┬─────────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name          ┆ … ┆ Embarked_nul ┆ Title ┆ Rank  ┆ Sex_Encoded │
│ ---         ┆ ---      ┆ ---    ┆ ---           ┆   ┆ l            ┆ ---   ┆ ---   ┆ ---         │
│ i64         ┆ str      ┆ i64    ┆ str           ┆   ┆ ---          ┆ str   ┆ bool  ┆ u32         │
│             ┆          ┆        ┆               ┆   ┆ u8           ┆       ┆       ┆             │
╞═════════════╪══════════╪════════╪═══════════════╪═══╪══════════════╪═══════╪═══════╪═════════════╡
│ 1           ┆ No       ┆ 3      ┆ Braund, Mr.   ┆ … ┆ 0            ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ Owen Harris   ┆   ┆              ┆       ┆       ┆             │
│ 2           ┆ Yes      ┆ 1      ┆ Cumings, Mrs. ┆ … ┆ 0            ┆ Mrs   ┆ false ┆ 1           │
│             ┆          ┆        ┆ John Bradley  ┆   ┆              ┆       ┆       ┆             │
│             ┆          ┆        ┆ (Fl…          ┆   ┆              ┆       ┆       ┆             │
│ 3           ┆ Yes      ┆ 3      ┆ Heikkinen,    ┆ … ┆ 0            ┆ Miss  ┆ false ┆ 1           │
│             ┆          ┆        ┆ Miss. Laina   ┆   ┆              ┆       ┆       ┆             │
│ 4           ┆ Yes      ┆ 1      ┆ Futrelle,     ┆ … ┆ 0            ┆ Mrs   ┆ false ┆ 1           │
│             ┆          ┆        ┆ Mrs. Jacques  ┆   ┆              ┆       ┆       ┆             │
│             ┆          ┆        ┆ Heath (…      ┆   ┆              ┆       ┆       ┆             │
│ 5           ┆ No       ┆ 3      ┆ Allen, Mr.    ┆ … ┆ 0            ┆ Mr    ┆ false ┆ 0           │
│             ┆          ┆        ┆ William Henry ┆   ┆              ┆       ┆       ┆             │
└─────────────┴──────────┴────────┴───────────────┴───┴──────────────┴───────┴───────┴─────────────┘

## Part 6: Conclusions

Based on your analysis, what interesting relationships did you find? Write three interesting facts the museum can use in their exhibit.

> From a purely visual evaluation, it appears that gender and passenger fare class had the biggest impact on survival rates. There's probably a deeper story about socio-economic class distinction hidden here.
>
> Other factors such as familial connections weren't explored, but likely also played a role.

## 🌟 Above and Beyond 🌟

1. There appears to be a lot of different variations of similar titles. (such as abbreviations for Miss and Mademoiselle).

   Scan through the different titles to see which titles can be consolidated, then use what you know about data manipulation to simplify the distribution.

   Once you've finished, check the visualizations again to see if that made any difference.

2. The museum curator has room for a couple of nice visualizations for the exhibit. Create additional visualizations that are suitable for public display.