In [8]:
# Load some test data
import polars as pl
mpg = pl.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/mpg.csv', schema_overrides={'mpg': pl.Float64})
mpg

shape: (398, 9)
┌──────┬───────────┬──────────────┬────────────┬───┬──────────────┬──────┬────────┬────────────────┐
│ mpg  ┆ cylinders ┆ displacement ┆ horsepower ┆ … ┆ acceleration ┆ year ┆ origin ┆ name           │
│ ---  ┆ ---       ┆ ---          ┆ ---        ┆   ┆ ---          ┆ ---  ┆ ---    ┆ ---            │
│ f64  ┆ i64       ┆ f64          ┆ str        ┆   ┆ f64          ┆ i64  ┆ i64    ┆ str            │
╞══════╪═══════════╪══════════════╪════════════╪═══╪══════════════╪══════╪════════╪════════════════╡
│ 18.0 ┆ 8         ┆ 307.0        ┆ 130        ┆ … ┆ 12.0         ┆ 70   ┆ 1      ┆ chevrolet      │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ chevelle       │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ malibu         │
│ 15.0 ┆ 8         ┆ 350.0        ┆ 165        ┆ … ┆ 11.5         ┆ 70   ┆ 1      ┆ buick skylark  │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ 320            │
│ 18.0 ┆ 8         ┆ 318.0        ┆ 150        ┆ … ┆ 11.0         ┆ 70   ┆ 1      ┆ plymouth       │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ satellite      │
│ 16.0 ┆ 8         ┆ 304.0        ┆ 150        ┆ … ┆ 12.0         ┆ 70   ┆ 1      ┆ amc rebel sst  │
│ 17.0 ┆ 8         ┆ 302.0        ┆ 140        ┆ … ┆ 10.5         ┆ 70   ┆ 1      ┆ ford torino    │
│ …    ┆ …         ┆ …            ┆ …          ┆ … ┆ …            ┆ …    ┆ …      ┆ …              │
│ 27.0 ┆ 4         ┆ 140.0        ┆ 86         ┆ … ┆ 15.6         ┆ 82   ┆ 1      ┆ ford mustang   │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ gl             │
│ 44.0 ┆ 4         ┆ 97.0         ┆ 52         ┆ … ┆ 24.6         ┆ 82   ┆ 2      ┆ vw pickup      │
│ 32.0 ┆ 4         ┆ 135.0        ┆ 84         ┆ … ┆ 11.6         ┆ 82   ┆ 1      ┆ dodge rampage  │
│ 28.0 ┆ 4         ┆ 120.0        ┆ 79         ┆ … ┆ 18.6         ┆ 82   ┆ 1      ┆ ford ranger    │
│ 31.0 ┆ 4         ┆ 119.0        ┆ 82         ┆ … ┆ 19.4         ┆ 82   ┆ 1      ┆ chevy s-10     │
└──────┴───────────┴──────────────┴────────────┴───┴──────────────┴──────┴────────┴────────────────┘

In [9]:
# Import the libraries we need
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split

In [10]:
# Horsepower has some missing values, represented as '?'
mpg.filter(pl.col('horsepower')== '?')

shape: (6, 9)
┌──────┬───────────┬──────────────┬────────────┬───┬──────────────┬──────┬────────┬────────────────┐
│ mpg  ┆ cylinders ┆ displacement ┆ horsepower ┆ … ┆ acceleration ┆ year ┆ origin ┆ name           │
│ ---  ┆ ---       ┆ ---          ┆ ---        ┆   ┆ ---          ┆ ---  ┆ ---    ┆ ---            │
│ f64  ┆ i64       ┆ f64          ┆ str        ┆   ┆ f64          ┆ i64  ┆ i64    ┆ str            │
╞══════╪═══════════╪══════════════╪════════════╪═══╪══════════════╪══════╪════════╪════════════════╡
│ 25.0 ┆ 4         ┆ 98.0         ┆ ?          ┆ … ┆ 19.0         ┆ 71   ┆ 1      ┆ ford pinto     │
│ 21.0 ┆ 6         ┆ 200.0        ┆ ?          ┆ … ┆ 17.0         ┆ 74   ┆ 1      ┆ ford maverick  │
│ 40.9 ┆ 4         ┆ 85.0         ┆ ?          ┆ … ┆ 17.3         ┆ 80   ┆ 2      ┆ renault lecar  │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ deluxe         │
│ 23.6 ┆ 4         ┆ 140.0        ┆ ?          ┆ … ┆ 14.3         ┆ 80   ┆ 1      ┆ ford mustang   │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ cobra          │
│ 34.5 ┆ 4         ┆ 100.0        ┆ ?          ┆ … ┆ 15.8         ┆ 81   ┆ 2      ┆ renault 18i    │
│ 23.0 ┆ 4         ┆ 151.0        ┆ ?          ┆ … ┆ 20.5         ┆ 82   ┆ 1      ┆ amc concord dl │
└──────┴───────────┴──────────────┴────────────┴───┴──────────────┴──────┴────────┴────────────────┘

In [11]:
# Get our target variable and features and split them into test and train datasets

X = mpg[['cylinders', 'displacement', 'acceleration', 'weight']]
y = mpg['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Create the model and train it, use default hyperparameters for now
model = XGBRegressor()
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [13]:
# Get predictions for our test data
predictions = model.predict(X_test)
predictions

array([38.657696, 28.087242, 23.523146, 17.897999, 15.234213, 27.013454,
       22.056187, 11.940811, 16.265862, 19.103987, 13.940032, 31.308727,
       35.01516 , 16.411985, 26.870445, 13.404857, 27.392363, 19.531116,
       13.77361 , 37.423004, 35.091824, 18.268314, 18.177662, 30.06011 ,
       15.404021, 25.241917, 29.574886, 26.355955, 20.4689  , 10.909517,
       22.864702, 31.812233, 18.264406, 23.914774, 35.1818  , 14.921148,
       25.206757, 20.949095, 13.071755, 28.7247  , 23.589334, 25.701653,
       22.081858, 13.138733, 31.13615 , 27.268324, 24.874348, 25.438108,
       26.179909, 27.972618, 18.926208, 29.807665, 31.330664, 13.662537,
       25.912758, 13.90974 , 15.214119, 23.43225 , 25.944368, 21.094381,
       14.643568, 37.514183, 26.335974, 29.254011, 19.77668 , 23.710693,
       26.440866, 32.163937, 25.943663, 14.524177, 32.345703, 12.65041 ,
       14.335071, 27.323072, 20.730164, 21.49504 , 17.644854, 28.044266,
       29.646917, 15.890411], dtype=float32)

In [14]:
# Compute the Root Mean Squared Error of the predictions
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

result = root_mean_squared_error(y_test, predictions)
print(f'Root Mean Squared Error: {result}')

result = r2_score(y_test, predictions)
print(f'R2 Score: {result}')

# Looks like we're off by just 4.3 mpg on average
# Not bad for a quick run with no real preprocessing

Root Mean Squared Error: 4.357173442840576
R2 Score: 0.6468994617462158