In [ ]:
# Load some test data
import polars as pl
mpg = pl.read_csv('https://raw.githubusercontent.com/byui-cse/cse450-course/master/data/mpg.csv', infer_schema_length=None)
mpg.head()

shape: (5, 9)
┌──────┬───────────┬──────────────┬────────────┬───┬──────────────┬──────┬────────┬────────────────┐
│ mpg  ┆ cylinders ┆ displacement ┆ horsepower ┆ … ┆ acceleration ┆ year ┆ origin ┆ name           │
│ ---  ┆ ---       ┆ ---          ┆ ---        ┆   ┆ ---          ┆ ---  ┆ ---    ┆ ---            │
│ f64  ┆ i64       ┆ f64          ┆ str        ┆   ┆ f64          ┆ i64  ┆ i64    ┆ str            │
╞══════╪═══════════╪══════════════╪════════════╪═══╪══════════════╪══════╪════════╪════════════════╡
│ 18.0 ┆ 8         ┆ 307.0        ┆ 130        ┆ … ┆ 12.0         ┆ 70   ┆ 1      ┆ chevrolet      │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ chevelle       │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ malibu         │
│ 15.0 ┆ 8         ┆ 350.0        ┆ 165        ┆ … ┆ 11.5         ┆ 70   ┆ 1      ┆ buick skylark  │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ 320            │
│ 18.0 ┆ 8         ┆ 318.0        ┆ 150        ┆ … ┆ 11.0         ┆ 70   ┆ 1      ┆ plymouth       │
│      ┆           ┆              ┆            ┆   ┆              ┆      ┆        ┆ satellite      │
│ 16.0 ┆ 8         ┆ 304.0        ┆ 150        ┆ … ┆ 12.0         ┆ 70   ┆ 1      ┆ amc rebel sst  │
│ 17.0 ┆ 8         ┆ 302.0        ┆ 140        ┆ … ┆ 10.5         ┆ 70   ┆ 1      ┆ ford torino    │
└──────┴───────────┴──────────────┴────────────┴───┴──────────────┴──────┴────────┴────────────────┘

In [ ]:
mpg.describe()

shape: (9, 10)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ statistic  ┆ mpg       ┆ cylinders ┆ displacem ┆ … ┆ accelerat ┆ year     ┆ origin   ┆ name      │
│ ---        ┆ ---       ┆ ---       ┆ ent       ┆   ┆ ion       ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ f64       ┆ f64       ┆ ---       ┆   ┆ ---       ┆ f64      ┆ f64      ┆ str       │
│            ┆           ┆           ┆ f64       ┆   ┆ f64       ┆          ┆          ┆           │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ count      ┆ 398.0     ┆ 398.0     ┆ 398.0     ┆ … ┆ 398.0     ┆ 398.0    ┆ 398.0    ┆ 398       │
│ null_count ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0      ┆ 0.0      ┆ 0         │
│ mean       ┆ 23.514573 ┆ 5.454774  ┆ 193.42587 ┆ … ┆ 15.56809  ┆ 76.01005 ┆ 1.572864 ┆ null      │
│            ┆           ┆           ┆ 9         ┆   ┆           ┆          ┆          ┆           │
│ std        ┆ 7.815984  ┆ 1.701004  ┆ 104.26983 ┆ … ┆ 2.757689  ┆ 3.697627 ┆ 0.802055 ┆ null      │
│            ┆           ┆           ┆ 8         ┆   ┆           ┆          ┆          ┆           │
│ min        ┆ 9.0       ┆ 3.0       ┆ 68.0      ┆ … ┆ 8.0       ┆ 70.0     ┆ 1.0      ┆ amc ambas │
│            ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆ sador     │
│            ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆ brougham  │
│ 25%        ┆ 17.5      ┆ 4.0       ┆ 104.0     ┆ … ┆ 13.8      ┆ 73.0     ┆ 1.0      ┆ null      │
│ 50%        ┆ 23.0      ┆ 4.0       ┆ 151.0     ┆ … ┆ 15.5      ┆ 76.0     ┆ 1.0      ┆ null      │
│ 75%        ┆ 29.0      ┆ 8.0       ┆ 262.0     ┆ … ┆ 17.2      ┆ 79.0     ┆ 2.0      ┆ null      │
│ max        ┆ 46.6      ┆ 8.0       ┆ 455.0     ┆ … ┆ 24.8      ┆ 82.0     ┆ 3.0      ┆ vw rabbit │
│            ┆           ┆           ┆           ┆   ┆           ┆          ┆          ┆ custom    │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴──────────┴───────────┘

In [ ]:
# Import the libraries we need
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Commonly used modules
import numpy as np

# Images, plots, display, and visualization
%pip install lets-plot
from lets_plot import *
LetsPlot.setup_html()
import matplotlib.pyplot as plt
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import root_mean_squared_error, r2_score

Requirement already satisfied: lets-plot in /usr/local/lib/python3.12/dist-packages (4.10.1)
Requirement already satisfied: pypng in /usr/local/lib/python3.12/dist-packages (from lets-plot) (0.20220715.0)
Requirement already satisfied: palettable in /usr/local/lib/python3.12/dist-packages (from lets-plot) (3.3.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from lets-plot) (11.3.0)

In [ ]:
# need to deal with ?s in the data
mpg[32,'horsepower'] = 72
mpg[126,'horsepower'] = 85
mpg[330,'horsepower'] = 64
mpg[354,'horsepower'] = 83
mpg[336,'horsepower'] = 75
mpg[374,'horsepower'] = 90
mpg = mpg.with_columns(pl.col('horsepower').cast(pl.Int64))

In [ ]:
# one hot encode origin
mpg = mpg.with_columns(pl.col('origin').replace_strict({1: 'USA', 2: 'Europe', 3: 'Japan'}))

mpg = mpg.to_dummies(columns=['origin'])

In [ ]:
mpg

shape: (398, 11)
┌──────┬───────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ mpg  ┆ cylinders ┆ displaceme ┆ horsepower ┆ … ┆ origin_Eur ┆ origin_Jap ┆ origin_US ┆ name      │
│ ---  ┆ ---       ┆ nt         ┆ ---        ┆   ┆ ope        ┆ an         ┆ A         ┆ ---       │
│ f64  ┆ i64       ┆ ---        ┆ i64        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ str       │
│      ┆           ┆ f64        ┆            ┆   ┆ u8         ┆ u8         ┆ u8        ┆           │
╞══════╪═══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 18.0 ┆ 8         ┆ 307.0      ┆ 130        ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ chevrolet │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ chevelle  │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ malibu    │
│ 15.0 ┆ 8         ┆ 350.0      ┆ 165        ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ buick     │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ skylark   │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ 320       │
│ 18.0 ┆ 8         ┆ 318.0      ┆ 150        ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ plymouth  │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ satellite │
│ 16.0 ┆ 8         ┆ 304.0      ┆ 150        ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ amc rebel │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ sst       │
│ 17.0 ┆ 8         ┆ 302.0      ┆ 140        ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ ford      │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ torino    │
│ …    ┆ …         ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 27.0 ┆ 4         ┆ 140.0      ┆ 86         ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ ford      │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ mustang   │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ gl        │
│ 44.0 ┆ 4         ┆ 97.0       ┆ 52         ┆ … ┆ 1          ┆ 0          ┆ 0         ┆ vw pickup │
│ 32.0 ┆ 4         ┆ 135.0      ┆ 84         ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ dodge     │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ rampage   │
│ 28.0 ┆ 4         ┆ 120.0      ┆ 79         ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ ford      │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ ranger    │
│ 31.0 ┆ 4         ┆ 119.0      ┆ 82         ┆ … ┆ 0          ┆ 0          ┆ 1         ┆ chevy     │
│      ┆           ┆            ┆            ┆   ┆            ┆            ┆           ┆ s-10      │
└──────┴───────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [ ]:
X = mpg.drop("mpg","name")
y = mpg.select("mpg")

In [ ]:
# look at data, now it is all numeric
X

shape: (398, 9)
┌───────────┬─────────────┬────────────┬────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ cylinders ┆ displacemen ┆ horsepower ┆ weight ┆ … ┆ year ┆ origin_Euro ┆ origin_Jap ┆ origin_USA │
│ ---       ┆ t           ┆ ---        ┆ ---    ┆   ┆ ---  ┆ pe          ┆ an         ┆ ---        │
│ i64       ┆ ---         ┆ i64        ┆ i64    ┆   ┆ i64  ┆ ---         ┆ ---        ┆ u8         │
│           ┆ f64         ┆            ┆        ┆   ┆      ┆ u8          ┆ u8         ┆            │
╞═══════════╪═════════════╪════════════╪════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ 8         ┆ 307.0       ┆ 130        ┆ 3504   ┆ … ┆ 70   ┆ 0           ┆ 0          ┆ 1          │
│ 8         ┆ 350.0       ┆ 165        ┆ 3693   ┆ … ┆ 70   ┆ 0           ┆ 0          ┆ 1          │
│ 8         ┆ 318.0       ┆ 150        ┆ 3436   ┆ … ┆ 70   ┆ 0           ┆ 0          ┆ 1          │
│ 8         ┆ 304.0       ┆ 150        ┆ 3433   ┆ … ┆ 70   ┆ 0           ┆ 0          ┆ 1          │
│ 8         ┆ 302.0       ┆ 140        ┆ 3449   ┆ … ┆ 70   ┆ 0           ┆ 0          ┆ 1          │
│ …         ┆ …           ┆ …          ┆ …      ┆ … ┆ …    ┆ …           ┆ …          ┆ …          │
│ 4         ┆ 140.0       ┆ 86         ┆ 2790   ┆ … ┆ 82   ┆ 0           ┆ 0          ┆ 1          │
│ 4         ┆ 97.0        ┆ 52         ┆ 2130   ┆ … ┆ 82   ┆ 1           ┆ 0          ┆ 0          │
│ 4         ┆ 135.0       ┆ 84         ┆ 2295   ┆ … ┆ 82   ┆ 0           ┆ 0          ┆ 1          │
│ 4         ┆ 120.0       ┆ 79         ┆ 2625   ┆ … ┆ 82   ┆ 0           ┆ 0          ┆ 1          │
│ 4         ┆ 119.0       ┆ 82         ┆ 2720   ┆ … ┆ 82   ┆ 0           ┆ 0          ┆ 1          │
└───────────┴─────────────┴────────────┴────────┴───┴──────┴─────────────┴────────────┴────────────┘

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
y_train

shape: (278, 1)
┌──────┐
│ mpg  │
│ ---  │
│ f64  │
╞══════╡
│ 15.0 │
│ 21.0 │
│ 21.0 │
│ 20.5 │
│ 21.0 │
│ …    │
│ 19.0 │
│ 12.0 │
│ 21.1 │
│ 37.7 │
│ 26.0 │
└──────┘

In [ ]:
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(X_train)

# transform training data
X_train = norm.transform(X_train)

# transform testing dataabs
X_test = norm.transform(X_test)

In [ ]:
# len(X_train[0])

In [ ]:
# build a neural network using a sequential model
# input layer node size is the same as the training columns
# hidden layers: 128 node layer, 256 node layer, 64 node layer
# a single node output layer
model = Sequential()
model.add(Dense(128, input_dim=len(X_train[0]), activation='relu'))
model.add(Dropout(.5))
model.add(Dense(256, activation='relu'))
model.add(Dense(64, activation='leaky_relu'))

model.add(Dense(1, activation='relu'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 128)            │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 256)            │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 50,817 (198.50 KB)

 Trainable params: 50,817 (198.50 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# opt = keras.optimizers.Adam(learning_rate=0.0001)
opt = keras.optimizers.Adam()
model.compile(loss="mean_squared_error", optimizer=opt, metrics=['mse'])

In [ ]:
early_stop = keras.callbacks.EarlyStopping(monitor='val_mse', patience=30)

history = model.fit(X_train, y_train, epochs=2000, validation_split=.35, batch_size=20, callbacks=[early_stop],shuffle=False)
# history = model.fit(train_features, train_labels, epochs=2000, verbose=0, validation_split = .2, batch_size=tester2,
#                     callbacks=[early_stop, PrintDot()])

hist = pl.DataFrame(history.history)

Epoch 1/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 6s 164ms/step - loss: 602.0081 - mse: 602.0081 - val_loss: 574.7354 - val_mse: 574.7354
Epoch 2/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 532.9156 - mse: 532.9156 - val_loss: 474.6080 - val_mse: 474.6080
Epoch 3/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 383.8315 - mse: 383.8315 - val_loss: 263.6950 - val_mse: 263.6950
Epoch 4/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 175.5519 - mse: 175.5519 - val_loss: 117.9031 - val_mse: 117.9031
Epoch 5/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 123.6004 - mse: 123.6004 - val_loss: 89.7916 - val_mse: 89.7916
Epoch 6/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 71.1591 - mse: 71.1591 - val_loss: 66.8156 - val_mse: 66.8156
Epoch 7/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 55.8539 - mse: 55.8539 - val_loss: 50.6758 - val_mse: 50.6758
Epoch 8/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 47.7789 - mse: 47.7789 - val_loss: 40.6460 - val_mse: 40.6460
Epoch 9/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 41.1043 - mse: 41.1043 - val_loss: 36.0848 - val_mse: 36.0848
Epoch 10/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 38.3522 - mse: 38.3522 - val_loss: 34.4630 - val_mse: 34.4630
Epoch 11/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 33.4367 - mse: 33.4367 - val_loss: 28.6143 - val_mse: 28.6143
Epoch 12/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 26.2231 - mse: 26.2231 - val_loss: 25.1717 - val_mse: 25.1717
Epoch 13/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 28.4968 - mse: 28.4968 - val_loss: 23.2018 - val_mse: 23.2018
Epoch 14/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.4003 - mse: 26.4003 - val_loss: 21.6060 - val_mse: 21.6060
Epoch 15/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 27.1610 - mse: 27.1610 - val_loss: 20.5002 - val_mse: 20.5002
Epoch 16/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 28.3775 - mse: 28.3775 - val_loss: 19.8375 - val_mse: 19.8375
Epoch 17/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25.6694 - mse: 25.6694 - val_loss: 17.7715 - val_mse: 17.7715
Epoch 18/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 22.2850 - mse: 22.2850 - val_loss: 17.6746 - val_mse: 17.6746
Epoch 19/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17.4541 - mse: 17.4541 - val_loss: 17.3672 - val_mse: 17.3672
Epoch 20/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.5479 - mse: 18.5479 - val_loss: 16.1974 - val_mse: 16.1974
Epoch 21/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.3040 - mse: 19.3040 - val_loss: 15.7779 - val_mse: 15.7779
Epoch 22/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.5213 - mse: 21.5213 - val_loss: 14.7955 - val_mse: 14.7955
Epoch 23/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19.1076 - mse: 19.1076 - val_loss: 14.4689 - val_mse: 14.4689
Epoch 24/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.0306 - mse: 19.0306 - val_loss: 13.6676 - val_mse: 13.6676
Epoch 25/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.6491 - mse: 16.6491 - val_loss: 15.0747 - val_mse: 15.0747
Epoch 26/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.1078 - mse: 19.1078 - val_loss: 13.9956 - val_mse: 13.9956
Epoch 27/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.9039 - mse: 22.9039 - val_loss: 13.8218 - val_mse: 13.8218
Epoch 28/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17.3413 - mse: 17.3413 - val_loss: 14.1314 - val_mse: 14.1314
Epoch 29/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.9740 - mse: 13.9740 - val_loss: 13.7540 - val_mse: 13.7540
Epoch 30/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.9226 - mse: 22.9226 - val_loss: 13.8748 - val_mse: 13.8748
Epoch 31/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.9690 - mse: 18.9690 - val_loss: 15.5395 - val_mse: 15.5395
Epoch 32/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 17.6428 - mse: 17.6428 - val_loss: 12.6257 - val_mse: 12.6257
Epoch 33/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17.3032 - mse: 17.3032 - val_loss: 12.9526 - val_mse: 12.9526
Epoch 34/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.4323 - mse: 18.4323 - val_loss: 13.7235 - val_mse: 13.7235
Epoch 35/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.5522 - mse: 16.5522 - val_loss: 12.4201 - val_mse: 12.4201
Epoch 36/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.6856 - mse: 15.6856 - val_loss: 11.6891 - val_mse: 11.6891
Epoch 37/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.9947 - mse: 18.9947 - val_loss: 11.5257 - val_mse: 11.5257
Epoch 38/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 17.4558 - mse: 17.4558 - val_loss: 13.2259 - val_mse: 13.2259
Epoch 39/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 18.2414 - mse: 18.2414 - val_loss: 11.7969 - val_mse: 11.7969
Epoch 40/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.8892 - mse: 16.8892 - val_loss: 12.9279 - val_mse: 12.9279
Epoch 41/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.9106 - mse: 14.9106 - val_loss: 10.7072 - val_mse: 10.7072
Epoch 42/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.6350 - mse: 12.6350 - val_loss: 11.3053 - val_mse: 11.3053
Epoch 43/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.6648 - mse: 14.6648 - val_loss: 11.5060 - val_mse: 11.5060
Epoch 44/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.6670 - mse: 14.6670 - val_loss: 10.3568 - val_mse: 10.3568
Epoch 45/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.5080 - mse: 19.5080 - val_loss: 11.2656 - val_mse: 11.2656
Epoch 46/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.0112 - mse: 15.0112 - val_loss: 10.5924 - val_mse: 10.5924
Epoch 47/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.6196 - mse: 15.6196 - val_loss: 14.5447 - val_mse: 14.5447
Epoch 48/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.7946 - mse: 16.7946 - val_loss: 10.9504 - val_mse: 10.9504
Epoch 49/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.4573 - mse: 15.4573 - val_loss: 13.2124 - val_mse: 13.2124
Epoch 50/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.4803 - mse: 13.4803 - val_loss: 10.3933 - val_mse: 10.3933
Epoch 51/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.0420 - mse: 15.0420 - val_loss: 12.2558 - val_mse: 12.2558
Epoch 52/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.4311 - mse: 15.4311 - val_loss: 11.2132 - val_mse: 11.2132
Epoch 53/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.8203 - mse: 16.8203 - val_loss: 11.0275 - val_mse: 11.0275
Epoch 54/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.6251 - mse: 14.6251 - val_loss: 10.2790 - val_mse: 10.2790
Epoch 55/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 16.1306 - mse: 16.1306 - val_loss: 11.9939 - val_mse: 11.9939
Epoch 56/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 16.4449 - mse: 16.4449 - val_loss: 9.8520 - val_mse: 9.8520
Epoch 57/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 14.1630 - mse: 14.1630 - val_loss: 11.7730 - val_mse: 11.7730
Epoch 58/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 13.8482 - mse: 13.8482 - val_loss: 10.2850 - val_mse: 10.2850
Epoch 59/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 13.7917 - mse: 13.7917 - val_loss: 11.9521 - val_mse: 11.9521
Epoch 60/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 14.0598 - mse: 14.0598 - val_loss: 10.3895 - val_mse: 10.3895
Epoch 61/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 12.1591 - mse: 12.1591 - val_loss: 9.4420 - val_mse: 9.4420
Epoch 62/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 13.1888 - mse: 13.1888 - val_loss: 10.2496 - val_mse: 10.2496
Epoch 63/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 15.7157 - mse: 15.7157 - val_loss: 10.3242 - val_mse: 10.3242
Epoch 64/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.2588 - mse: 14.2588 - val_loss: 10.9219 - val_mse: 10.9219
Epoch 65/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.7983 - mse: 14.7983 - val_loss: 9.5606 - val_mse: 9.5606
Epoch 66/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.7076 - mse: 11.7076 - val_loss: 10.9819 - val_mse: 10.9819
Epoch 67/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.0595 - mse: 13.0595 - val_loss: 10.1970 - val_mse: 10.1970
Epoch 68/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 16.1305 - mse: 16.1305 - val_loss: 9.5366 - val_mse: 9.5366
Epoch 69/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.0682 - mse: 13.0682 - val_loss: 10.0109 - val_mse: 10.0109
Epoch 70/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.3816 - mse: 11.3816 - val_loss: 9.2481 - val_mse: 9.2481
Epoch 71/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.1287 - mse: 13.1287 - val_loss: 9.3430 - val_mse: 9.3430
Epoch 72/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.4566 - mse: 11.4566 - val_loss: 9.5969 - val_mse: 9.5969
Epoch 73/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.5606 - mse: 13.5606 - val_loss: 9.5417 - val_mse: 9.5417
Epoch 74/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.9501 - mse: 12.9501 - val_loss: 8.9150 - val_mse: 8.9150
Epoch 75/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.5384 - mse: 13.5384 - val_loss: 10.4780 - val_mse: 10.4780
Epoch 76/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.3617 - mse: 14.3617 - val_loss: 8.5825 - val_mse: 8.5825
Epoch 77/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.1542 - mse: 13.1542 - val_loss: 9.7963 - val_mse: 9.7963
Epoch 78/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.0341 - mse: 15.0341 - val_loss: 8.8752 - val_mse: 8.8752
Epoch 79/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.3751 - mse: 14.3751 - val_loss: 9.6732 - val_mse: 9.6732
Epoch 80/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.0742 - mse: 14.0742 - val_loss: 9.9397 - val_mse: 9.9397
Epoch 81/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.6201 - mse: 13.6201 - val_loss: 9.8371 - val_mse: 9.8371
Epoch 82/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.9485 - mse: 12.9485 - val_loss: 9.4815 - val_mse: 9.4815
Epoch 83/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.3340 - mse: 12.3340 - val_loss: 8.6938 - val_mse: 8.6938
Epoch 84/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.8573 - mse: 10.8573 - val_loss: 10.4402 - val_mse: 10.4402
Epoch 85/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.9579 - mse: 10.9579 - val_loss: 9.1143 - val_mse: 9.1143
Epoch 86/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.2205 - mse: 11.2205 - val_loss: 10.7895 - val_mse: 10.7895
Epoch 87/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 12.5403 - mse: 12.5403 - val_loss: 8.8201 - val_mse: 8.8201
Epoch 88/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.1660 - mse: 11.1660 - val_loss: 9.3528 - val_mse: 9.3528
Epoch 89/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 12.6866 - mse: 12.6866 - val_loss: 9.4259 - val_mse: 9.4259
Epoch 90/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.3882 - mse: 13.3882 - val_loss: 9.7540 - val_mse: 9.7540
Epoch 91/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.7686 - mse: 13.7686 - val_loss: 8.4562 - val_mse: 8.4562
Epoch 92/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.2424 - mse: 13.2424 - val_loss: 10.6547 - val_mse: 10.6547
Epoch 93/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.3243 - mse: 12.3243 - val_loss: 8.4107 - val_mse: 8.4107
Epoch 94/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 10.0830 - mse: 10.0830 - val_loss: 10.0802 - val_mse: 10.0802
Epoch 95/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.2078 - mse: 10.2078 - val_loss: 10.0860 - val_mse: 10.0860
Epoch 96/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 12.4991 - mse: 12.4991 - val_loss: 9.2353 - val_mse: 9.2353
Epoch 97/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.8257 - mse: 11.8257 - val_loss: 8.7643 - val_mse: 8.7643
Epoch 98/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 14.8254 - mse: 14.8254 - val_loss: 9.6577 - val_mse: 9.6577
Epoch 99/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.0454 - mse: 10.0454 - val_loss: 8.9796 - val_mse: 8.9796
Epoch 100/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.1178 - mse: 11.1178 - val_loss: 9.2870 - val_mse: 9.2870
Epoch 101/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.2879 - mse: 13.2879 - val_loss: 8.7593 - val_mse: 8.7593
Epoch 102/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 11.5815 - mse: 11.5815 - val_loss: 9.5280 - val_mse: 9.5280
Epoch 103/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.9767 - mse: 10.9767 - val_loss: 9.5054 - val_mse: 9.5054
Epoch 104/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.8036 - mse: 10.8036 - val_loss: 9.1771 - val_mse: 9.1771
Epoch 105/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.9460 - mse: 9.9460 - val_loss: 8.8591 - val_mse: 8.8591
Epoch 106/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.1020 - mse: 12.1020 - val_loss: 10.1535 - val_mse: 10.1535
Epoch 107/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.9584 - mse: 10.9584 - val_loss: 9.6967 - val_mse: 9.6967
Epoch 108/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.6980 - mse: 10.6980 - val_loss: 9.2125 - val_mse: 9.2125
Epoch 109/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.9606 - mse: 9.9606 - val_loss: 9.6393 - val_mse: 9.6393
Epoch 110/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.3177 - mse: 11.3177 - val_loss: 8.8120 - val_mse: 8.8120
Epoch 111/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.3090 - mse: 9.3090 - val_loss: 10.6218 - val_mse: 10.6218
Epoch 112/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.7022 - mse: 10.7022 - val_loss: 8.4047 - val_mse: 8.4047
Epoch 113/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.9031 - mse: 12.9031 - val_loss: 8.8972 - val_mse: 8.8972
Epoch 114/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 8.9433 - mse: 8.9433 - val_loss: 8.7463 - val_mse: 8.7463
Epoch 115/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.2636 - mse: 11.2636 - val_loss: 9.5593 - val_mse: 9.5593
Epoch 116/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.3030 - mse: 12.3030 - val_loss: 8.7036 - val_mse: 8.7036
Epoch 117/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.5619 - mse: 9.5619 - val_loss: 9.8515 - val_mse: 9.8515
Epoch 118/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.0017 - mse: 11.0017 - val_loss: 9.9706 - val_mse: 9.9706
Epoch 119/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 10.1896 - mse: 10.1896 - val_loss: 9.0043 - val_mse: 9.0043
Epoch 120/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 11.1860 - mse: 11.1860 - val_loss: 9.6747 - val_mse: 9.6747
Epoch 121/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 11.5034 - mse: 11.5034 - val_loss: 8.9344 - val_mse: 8.9344
Epoch 122/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.0972 - mse: 8.0972 - val_loss: 8.9056 - val_mse: 8.9056
Epoch 123/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.4130 - mse: 10.4130 - val_loss: 9.1014 - val_mse: 9.1014
Epoch 124/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.2564 - mse: 11.2564 - val_loss: 8.8449 - val_mse: 8.8449
Epoch 125/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.8692 - mse: 10.8692 - val_loss: 9.3065 - val_mse: 9.3065
Epoch 126/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.0208 - mse: 9.0208 - val_loss: 9.2825 - val_mse: 9.2825
Epoch 127/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.5699 - mse: 10.5699 - val_loss: 9.5174 - val_mse: 9.5174
Epoch 128/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.0380 - mse: 11.0380 - val_loss: 9.0520 - val_mse: 9.0520
Epoch 129/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.6873 - mse: 11.6873 - val_loss: 10.0233 - val_mse: 10.0233
Epoch 130/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.0246 - mse: 12.0246 - val_loss: 9.4572 - val_mse: 9.4572
Epoch 131/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.5744 - mse: 9.5744 - val_loss: 9.4103 - val_mse: 9.4103
Epoch 132/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.7697 - mse: 8.7697 - val_loss: 9.4100 - val_mse: 9.4100
Epoch 133/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.6618 - mse: 9.6618 - val_loss: 8.8447 - val_mse: 8.8447
Epoch 134/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.5295 - mse: 9.5295 - val_loss: 9.9995 - val_mse: 9.9995
Epoch 135/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.5607 - mse: 8.5607 - val_loss: 8.5683 - val_mse: 8.5683
Epoch 136/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 12.0781 - mse: 12.0781 - val_loss: 9.2046 - val_mse: 9.2046
Epoch 137/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.2353 - mse: 10.2353 - val_loss: 9.8776 - val_mse: 9.8776
Epoch 138/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.5196 - mse: 9.5196 - val_loss: 9.8680 - val_mse: 9.8680
Epoch 139/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.9725 - mse: 10.9725 - val_loss: 9.2144 - val_mse: 9.2144
Epoch 140/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.0546 - mse: 11.0546 - val_loss: 8.9651 - val_mse: 8.9651
Epoch 141/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.8008 - mse: 11.8008 - val_loss: 8.2878 - val_mse: 8.2878
Epoch 142/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.6218 - mse: 9.6218 - val_loss: 8.7278 - val_mse: 8.7278
Epoch 143/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.5155 - mse: 10.5155 - val_loss: 9.2471 - val_mse: 9.2471
Epoch 144/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.5662 - mse: 9.5662 - val_loss: 8.6040 - val_mse: 8.6040
Epoch 145/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.7697 - mse: 10.7697 - val_loss: 10.3366 - val_mse: 10.3366
Epoch 146/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.5002 - mse: 9.5002 - val_loss: 8.5363 - val_mse: 8.5363
Epoch 147/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 11.0392 - mse: 11.0392 - val_loss: 10.2884 - val_mse: 10.2884
Epoch 148/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 10.4478 - mse: 10.4478 - val_loss: 8.4820 - val_mse: 8.4820
Epoch 149/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 10.0875 - mse: 10.0875 - val_loss: 8.6402 - val_mse: 8.6402
Epoch 150/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.7526 - mse: 9.7526 - val_loss: 8.1743 - val_mse: 8.1743
Epoch 151/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 11.1937 - mse: 11.1937 - val_loss: 10.4127 - val_mse: 10.4127
Epoch 152/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.0104 - mse: 9.0104 - val_loss: 8.1161 - val_mse: 8.1161
Epoch 153/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 10.1160 - mse: 10.1160 - val_loss: 9.8835 - val_mse: 9.8835
Epoch 154/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 9.7558 - mse: 9.7558 - val_loss: 8.3034 - val_mse: 8.3034
Epoch 155/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.4935 - mse: 9.4935 - val_loss: 11.6025 - val_mse: 11.6025
Epoch 156/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 9.2431 - mse: 9.2431 - val_loss: 8.4336 - val_mse: 8.4336
Epoch 157/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 9.3299 - mse: 9.3299 - val_loss: 9.8280 - val_mse: 9.8280
Epoch 158/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.6215 - mse: 8.6215 - val_loss: 8.9395 - val_mse: 8.9395
Epoch 159/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.9728 - mse: 9.9728 - val_loss: 10.9320 - val_mse: 10.9320
Epoch 160/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.3562 - mse: 9.3562 - val_loss: 8.4767 - val_mse: 8.4767
Epoch 161/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1686 - mse: 9.1686 - val_loss: 8.9242 - val_mse: 8.9242
Epoch 162/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.6533 - mse: 8.6533 - val_loss: 8.4984 - val_mse: 8.4984
Epoch 163/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.4774 - mse: 8.4774 - val_loss: 8.9256 - val_mse: 8.9256
Epoch 164/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.3422 - mse: 9.3422 - val_loss: 8.5341 - val_mse: 8.5341
Epoch 165/2000
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.5626 - mse: 9.5626 - val_loss: 9.9472 - val_mse: 9.9472
Epoch 166/2000

In [ ]:
hist

shape: (182, 4)
┌────────────┬────────────┬────────────┬────────────┐
│ loss       ┆ mse        ┆ val_loss   ┆ val_mse    │
│ ---        ┆ ---        ┆ ---        ┆ ---        │
│ f64        ┆ f64        ┆ f64        ┆ f64        │
╞════════════╪════════════╪════════════╪════════════╡
│ 602.008057 ┆ 602.008057 ┆ 574.735413 ┆ 574.735413 │
│ 532.915649 ┆ 532.915649 ┆ 474.608032 ┆ 474.608032 │
│ 383.831512 ┆ 383.831512 ┆ 263.695007 ┆ 263.695007 │
│ 175.551926 ┆ 175.551926 ┆ 117.903069 ┆ 117.903069 │
│ 123.600426 ┆ 123.600426 ┆ 89.791573  ┆ 89.791573  │
│ …          ┆ …          ┆ …          ┆ …          │
│ 10.067956  ┆ 10.067956  ┆ 8.758487   ┆ 8.758487   │
│ 11.043855  ┆ 11.043855  ┆ 8.454241   ┆ 8.454241   │
│ 8.417718   ┆ 8.417718   ┆ 8.553119   ┆ 8.553119   │
│ 8.191729   ┆ 8.191729   ┆ 8.621849   ┆ 8.621849   │
│ 9.712894   ┆ 9.712894   ┆ 9.288218   ┆ 9.288218   │
└────────────┴────────────┴────────────┴────────────┘

In [ ]:
# h = hist
hist = hist.with_row_index()
# h

In [ ]:
hist

shape: (182, 5)
┌───────┬────────────┬────────────┬────────────┬────────────┐
│ index ┆ loss       ┆ mse        ┆ val_loss   ┆ val_mse    │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ u32   ┆ f64        ┆ f64        ┆ f64        ┆ f64        │
╞═══════╪════════════╪════════════╪════════════╪════════════╡
│ 0     ┆ 602.008057 ┆ 602.008057 ┆ 574.735413 ┆ 574.735413 │
│ 1     ┆ 532.915649 ┆ 532.915649 ┆ 474.608032 ┆ 474.608032 │
│ 2     ┆ 383.831512 ┆ 383.831512 ┆ 263.695007 ┆ 263.695007 │
│ 3     ┆ 175.551926 ┆ 175.551926 ┆ 117.903069 ┆ 117.903069 │
│ 4     ┆ 123.600426 ┆ 123.600426 ┆ 89.791573  ┆ 89.791573  │
│ …     ┆ …          ┆ …          ┆ …          ┆ …          │
│ 177   ┆ 10.067956  ┆ 10.067956  ┆ 8.758487   ┆ 8.758487   │
│ 178   ┆ 11.043855  ┆ 11.043855  ┆ 8.454241   ┆ 8.454241   │
│ 179   ┆ 8.417718   ┆ 8.417718   ┆ 8.553119   ┆ 8.553119   │
│ 180   ┆ 8.191729   ┆ 8.191729   ┆ 8.621849   ┆ 8.621849   │
│ 181   ┆ 9.712894   ┆ 9.712894   ┆ 9.288218   ┆ 9.288218   │
└───────┴────────────┴────────────┴────────────┴────────────┘

In [ ]:
mse_hist = hist.drop(['loss', 'val_loss']).unpivot(index='index', variable_name='metric', value_name='mse').with_columns(pl.col('metric').replace({'mse': 'training error', 'val_mse': 'validation error'}))
mse_hist

shape: (364, 3)
┌───────┬──────────────────┬────────────┐
│ index ┆ metric           ┆ mse        │
│ ---   ┆ ---              ┆ ---        │
│ u32   ┆ str              ┆ f64        │
╞═══════╪══════════════════╪════════════╡
│ 0     ┆ training error   ┆ 602.008057 │
│ 1     ┆ training error   ┆ 532.915649 │
│ 2     ┆ training error   ┆ 383.831512 │
│ 3     ┆ training error   ┆ 175.551926 │
│ 4     ┆ training error   ┆ 123.600426 │
│ …     ┆ …                ┆ …          │
│ 177   ┆ validation error ┆ 8.758487   │
│ 178   ┆ validation error ┆ 8.454241   │
│ 179   ┆ validation error ┆ 8.553119   │
│ 180   ┆ validation error ┆ 8.621849   │
│ 181   ┆ validation error ┆ 9.288218   │
└───────┴──────────────────┴────────────┘

In [ ]:
(
    ggplot(data=mse_hist, mapping=aes(x='index', y='mse', color='metric'))
    + geom_line()
    + labs(x='Epoch', y='Mean Square Error')
    + theme_minimal()
    + theme(legend_title=element_blank())
)

In [ ]:
predictions = np.round(model.predict(X_test),1)

WARNING:tensorflow:5 out of the last 9 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7b26e30207c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step

WARNING:tensorflow:6 out of the last 12 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7b26e30207c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step

In [ ]:
predictions

array([[32.6],
       [29. ],
       [20.5],
       [15.1],
       [13.4],
       [24.7],
       [26.6],
       [12.6],
       [16.2],
       [19.7],
       [14. ],
       [36.9],
       [24.2],
       [14.1],
       [22.3],
       [12.4],
       [29.3],
       [20.5],
       [14.8],
       [37.1],
       [20.9],
       [19.4],
       [24.9],
       [27.7],
       [15.5],
       [41.1],
       [22.4],
       [22.6],
       [18.7],
       [12.8],
       [27.5],
       [36.5],
       [17.1],
       [23.4],
       [34.8],
       [13.2],
       [21.7],
       [17.9],
       [13.7],
       [23.2],
       [23.6],
       [25.9],
       [19.5],
       [11.8],
       [22.5],
       [33.6],
       [23.7],
       [20.8],
       [22.3],
       [25.8],
       [21.5],
       [33.8],
       [32.2],
       [12.8],
       [25.6],
       [12.9],
       [17. ],
       [28.5],
       [22.3],
       [18.2],
       [14.4],
       [31.5],
       [22. ],
       [19.3],
       [19.3],
       [23.3],
       [22.6],
       [33.3],
       [26.8],
       [13.9],
       [32.6],
       [13.6],
       [12.9],
       [18.3],
       [24.7],
       [19.5],
       [17.9],
       [28.5],
       [27.3],
       [17.6],
       [15.3],
       [23.8],
       [36.9],
       [34.1],
       [21.5],
       [13.1],
       [34.5],
       [30.7],
       [24.6],
       [12.5],
       [14.3],
       [30.1],
       [23. ],
       [33.5],
       [23.3],
       [34.3],
       [29.2],
       [20.1],
       [24.3],
       [13.5],
       [32. ],
       [23.7],
       [19.6],
       [14.9],
       [17.1],
       [13. ],
       [26.7],
       [13.1],
       [33.7],
       [36.7],
       [30.3],
       [24. ],
       [18.8],
       [37. ],
       [26. ],
       [20.9],
       [23.4],
       [19.7],
       [32.2],
       [19.2]], dtype=float32)

In [ ]:

result = root_mean_squared_error(y_test, predictions)
result

2.3708648681640625

In [ ]:

r2 = r2_score(y_test,predictions)
r2

0.9020584225654602

In [ ]:
pred = pl.DataFrame(predictions,schema=['predictions'])
y_test.columns = ['actual']
pred = pl.concat([pred, y_test], how='horizontal').with_columns(difference = pl.col('actual') - pl.col('predictions'))
display(pred)

shape: (120, 3)
┌─────────────┬────────┬────────────┐
│ predictions ┆ actual ┆ difference │
│ ---         ┆ ---    ┆ ---        │
│ f32         ┆ f64    ┆ f64        │
╞═════════════╪════════╪════════════╡
│ 32.599998   ┆ 33.0   ┆ 0.400002   │
│ 29.0        ┆ 28.0   ┆ -1.0       │
│ 20.5        ┆ 19.0   ┆ -1.5       │
│ 15.1        ┆ 13.0   ┆ -2.1       │
│ 13.4        ┆ 14.0   ┆ 0.6        │
│ …           ┆ …      ┆ …          │
│ 20.9        ┆ 20.0   ┆ -0.9       │
│ 23.4        ┆ 26.0   ┆ 2.6        │
│ 19.700001   ┆ 20.6   ┆ 0.899999   │
│ 32.200001   ┆ 37.3   ┆ 5.099999   │
│ 19.200001   ┆ 16.2   ┆ -3.000001  │
└─────────────┴────────┴────────────┘

In [ ]:
(
    ggplot(data=pred, mapping=aes(x='actual', y='predictions'))
    + geom_point(color='blue')
    + geom_smooth(method='lm', color='red', na_rm=True, se=False)
    + scale_x_continuous(limits=(5, 50))
    + scale_y_continuous(limits=(5, 50))
    + labs(x='Actual MPG', y='Predicted MPG')
    + theme_minimal()
)